@protocol=http
@host=localhost:5000
@endpointCreate=create-user
@endpointUpdate=update-user-data
@endpointFetch=fetch-user-data
@uid=ebuddy
@token=[REPLACE_WITH_API_KEY]

### Create User
POST {{protocol}}://{{host}}/{{endpointCreate}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "uid": "{{uid}}",
  "email": "ebuddy@ebuddy.com",
  "password": "pass123",
  "displayName": "ebuddy"
}

### Create User
POST {{protocol}}://{{host}}/{{endpointCreate}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "uid": "{{uid}}",
  "email": "ebuddy@ebuddy.com",
  "password": "pass123",
  "displayName": "ebuddy"
}

### Get User Data
GET {{protocol}}://{{host}}/{{endpointFetch}}/{{uid}} HTTP/1.1
Authorization: Bearer {{token}}

### Update User Data
PUT {{protocol}}://{{host}}/{{endpointUpdate}}/{{uid}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "firstName": "ebuddy",
  "lastName": "pte ltd"
}

### Get ID Token from Client Side
POST https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=[REPLACE_WITH_API_KEY]
Content-Type: application/json

{
  "email": "ebuddy@ebuddy.com",
  "password": "pass123",
  "returnSecureToken": true
}

### Signup
POST https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=[REPLACE_WITH_API_KEY]
Content-Type: application/json

{
  "email": "",
  "password": "",
  "returnSecureToken": true
}
